
set -g default-terminal "tmux-256color"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# Set mouse
set -g mouse on

# Vi copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-no-clear "xclip -selection clipboard"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "xclip -selection clipboard"

# Key bindings
unbind C-b
set -g prefix C-Space

# Splitting panes replace % and "
bind | split-window -h
bind - split-window -v

# moving between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resizeing panes
bind -n M-k resize-pane -U 10
bind -n M-j resize-pane -D 10
bind -n M-h resize-pane -L 10
bind -n M-l resize-pane -R 10

# statusbar
set -g status-position bottom
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100

set -ug status-right
set -ug status-left

# esc-time
set -sg escape-time 50

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Continuum config
set -g @continuum-restore 'on'

# Catppuccin config
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# update VSCODE variables from integrated terminal so that `code` command opens in current window
set-option -ga update-environment ' VSCODE_GIT_ASKPASS_NODE VSCODE_GIT_ASKPASS_MAIN VSCODE_IPC_HOOK_CLI PATH GIT_ASKPASS'
